ocmpHP/contact/urls.py
from django.urls import path
from . import views

app_name = 'contact'
urlpatterns = [
    path('', views.contact_page, name='contact_page'),
]

ocmpHP/members/urls.py
from django.urls import path
from . import views

app_name = 'members'
urlpatterns = [
    path('', views.member_page, name='member_page'),
]

ocmpHP/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('toppage.urls')), #root URL
    path('members/', include('members.urls')),
    path('contact/', include('contact.urls')),
    
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ocmpHP/toppage/urls.py
from django.urls import path
from . import views

app_name = 'toppage'
urlpatterns = [
    path('', views.index, name='index'),
]

ocmpHP/contact/models.py
from django.db import models

# Create your models here.

ocmpHP/members/models.py
from django.db import models

# Create your models here.
class Member(models.Model):
    name = models.CharField(max_length=100)
    name_roman = models.CharField(max_length=100)
    image = models.ImageField(upload_to='images/', null=True)
    research = models.CharField(max_length=100)
    comment = models.TextField()
    hometown = models.CharField(max_length=100)
    is_AssistantProfessor = models.BooleanField(default=False)
    is_Researcher = models.BooleanField(default=False)
    is_PhD = models.BooleanField(default=False)
    is_Master2 = models.BooleanField(default=False)
    is_Master1 = models.BooleanField(default=False)
    is_Bachelor = models.BooleanField(default=False)
    is_public = models.BooleanField(default=True)

    def __str__(self):
        return self.name

ocmpHP/toppage/models.py
from django.db import models

class Paper(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField()                # URLに含まれる文字列
    body = models.TextField()
    posted_date = models.DateTimeField(auto_now_add=True) # 日付を自動で追加

    def __str__(self): #オブジェクトのタイトルの設定
        return self.title

ocmpHP/contact/views.py
from django.shortcuts import render

# Create your views here.

def contact_page(request):
    return render(request, 'contact.html')

ocmpHP/members/views.py
from django.shortcuts import render
from .models import Member

# Create your views here.

def member_page(request):
    members_all = Member.objects.filter(is_public=True)
    members_PhD = Member.objects.filter(is_public=True, is_PhD=True)
    members_master2 = Member.objects.filter(is_public=True, is_Master2=True)
    members_master1 = Member.objects.filter(is_public=True, is_Master1=True)
    members_bachelor = Member.objects.filter(is_public=True, is_Bachelor=True)
    contents = {'members_all':members_all, 'members_PhD': members_PhD, 'members_master2': members_master2, 'members_master1': members_master1, 'members_bachelor': members_bachelor}
    return render(request, 'members.html', contents)

ocmpHP/toppage/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'toppage.html')

ocmpHP/templates/base.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    {% tailwind_css %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!--cssの読み込み-->
    <link href="{% static 'css/dist/styles.css' %}" rel="stylesheet"/>
    <!--box iconsの読み込み-->
    <link rel="stylesheet" href="boxicons.min.css">
    <!--google fontの読み込み-->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@300&family=Oswald:wght@500&display=swap" rel="stylesheet">
    <title>Satoh laboratory</title>
</head>
<body>
    <div class="header">
        <nav class="navbar">
            <h2 class="logo font-serif">Satoh laboratory</h2>
            <ul class="menu hidden">
                <li class="hover:bg-white hover:text-black rounded"><a href="" >home</a></li>
                <li class="hover:bg-white hover:text-black rounded"><a href="">研究内容</a></li>
                <li class="hover:bg-white hover:text-black rounded"><a href="">研究成果</a></li>
                <li class="hover:bg-white hover:text-black rounded"><a href="{% url 'members:member_page' %}">メンバー</a></li>
                <li class="hover:bg-white hover:text-black rounded"><a href="{% url 'contact:contact_page' %}">問い合わせ</a></li>
            </ul>
        </nav>
    </div>
    {% block content %}
    {% endblock %}
    <script>
        //scrollした時のheaderの挙動を設定．
        const navbar = document.querySelector(".navbar"); //nabbarの情報を取得
        console.log(navbar)//取得した情報の確認．
        const menu = document.querySelector(".menu")
        window.addEventListener("scroll",() => {
            //console.log(menu.offsetTop) //menu.offsetはmenuの上部からの高さを表すことを確認できる．
            if(window.pageYOffset >= 100){//window.pageYOffsetを100px以上スクロールしたら
                navbar.classList.add("sticky");//sticky classを付与．cssで定義する．
                menu.classList.remove("hidden");//リロード直後はhidden classが付与されているからmenuは表示されないが，一度スクロールして以降は表示されるようにする．
            } else { 
                navbar.classList.remove("sticky");
                menu.classList.add("hidden"); 
            }
        })//scrollするたびに{}内が実行される．
    </script>
</body>
</html>

ocmpHP/templates/contact.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div id="contact" class="bg_class" style="background-image: url({% static 'img/honkan.jpg' %});">
    <div class="spacer"></div>
    <div id="body" class="body">
        <div class="page_title">
            <h1>Contact</h1>
        </div>
        <div class="contact_info">
            佐藤研究室では、新しい研究分野を切り開く意志をもった卒研生、大学院生を募集しています。 理学院物理学系の大学院入学試験の案内はこちらです。 博士研究員を希望の方は、ご相談ください。 研究室見学を随時、歓迎しております。
            <br><br>
            <div class="contact_block">
                <h2>連絡先</h2>
                <p>佐藤 琢哉（教授）</p>
            </div>
            <div class="contact_block">
                <h2>所属</h2>
                <p>東京工業大学 理学院 物理学系 佐藤研究室</p>
            </div>
            <div class="contact_block">
                <h2>住所</h2>
                <p>〒152-8551 東京都目黒区大岡山2-12-1</p>
                <p>南5号館5階 502D(教授室) 507CD(学生居室)</p>
            </div>
            <div class="contact_block">
                <h2>電話番号(教授室)	</h2>
                <p>03-5734-2716</p>
            </div>
            <div class="contact_block">
                <h2>電話番号(学生居室)	</h2>
                <p>03-5734-2454</p>
            </div>
            <div class="contact_block">
                <h2>メール</h2>
                <img src="{% static 'img/satoh_mail.png' %}">
            </div>
            <br><br>
            
        </div>
    </div>
</div>

<script>
document.addEventListener("DOMContentLoaded", function() {
    setTimeout(function() {
        var contactElement = document.getElementById('contact');
        contactElement.style.opacity = "1";
        contactElement.style.visibility = "visible";
}, 100); // 0.1秒後に実行
});

//フェードインの設定
window.onload=function(){
    setTimeout(function(){
        var bodyelement = document.getElementById('body');
        bodyelement.classList.add('body_active');
    },1500);
}
</script>
{% endblock %}

ocmpHP/templates/member_templete/all_templete.html
{% load static %}
<div class="prof_templete">
    <div class="prof_body">
        <div class="prof_left" style="text-align: right;">
            <h2>三国 宏樹</h2>
            <br>
            東京工業大学 理学院物理学系 学生
            <br>
            <p>研究テーマ</p>
            スピントロニクス
            <br>
            <p>出身地</p>
            埼玉県
            <br>
            <p>ひとこと</p>
            ほげほげ
            <br>
            <p>出版物</p>
            <a href="">Google Scholar</a>
        </div>
        <div class="prof_right" style="text-align: left;">
            <p>学歴</p>
            2016-2019 栄東高等学校
            <br>
            2019-2023 千葉大学 理学部 物理学科
            <br>
            2023-2025 東京工業大学 理学院 物理学系
            <p>職歴</p>
            2025- 富士フイルム株式会社
            <br>
            2050 FIRE
            <p>受賞</p>
            2020 成人式
            <br>
            20XX ほげほげ
        </div>
    </div>
</div>

ocmpHP/templates/members.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div id="member" class="bg_class" style="background-image: url({% static 'img/members_all.png' %});">
    <div class="spacer"></div>
    <div id="body" class="body">
        <div class="page_title">
            <h1>Member</h1>
            <p>2024</p>
        </div>

        <div class="members_list">
            <h2>Professor</h2>
            <div class="flex items-center justify-center w-full px-5 py-6 mx-auto max-w-xl">
                <div id="satoh" class="bg-white shadow-xl rounded-xl overflow-hidden">
                    <img alt="team" class="w-32 h-32 mx-auto mt-4 rounded-full object-cover" src="https://storage.googleapis.com/indie-hackers.appspot.com/avatars/300x300_DUFTlhOdmSdoT9F4r1Woo40pyML2.webp">
                    <div class="p-6 text-center">
                        <h4 class="text-xl font-semibold leading-none tracking-tighter text-black">佐藤 琢哉</h4>
                        <p class="mt-2 text-base leading-relaxed text-gray-500">Satoh Takuya</p>
                    </div>
                </div>
            </div>
            <h2>Assistant professor</h2>
            <div class="flex items-center justify-center w-full px-5 py-6 mx-auto max-w-xl">
                <div id="yamada" class="bg-white shadow-xl rounded-xl overflow-hidden">
                    <img alt="team" class="w-32 h-32 mx-auto mt-4 rounded-full object-cover" src="https://storage.googleapis.com/indie-hackers.appspot.com/avatars/300x300_DUFTlhOdmSdoT9F4r1Woo40pyML2.webp">
                    <div class="p-6 text-center">
                        <h4 class="text-xl font-semibold leading-none tracking-tighter text-black">山田 貴大</h4>
                        <p class="mt-2 text-base leading-relaxed text-gray-500">Yamada Kihiro</p>
                    </div>
                </div>
            </div>
            <h2>Research staff / Professor emeritus</h2>
            <div class="flex items-center justify-center w-full px-5 py-6 mx-auto max-w-xl">
                <div id="munekata" class="bg-white shadow-xl rounded-xl overflow-hidden">
                    <img alt="team" class="w-32 h-32 mx-auto mt-4 rounded-full object-cover" src="https://storage.googleapis.com/indie-hackers.appspot.com/avatars/300x300_DUFTlhOdmSdoT9F4r1Woo40pyML2.webp">
                    <div class="p-6 text-center">
                        <h4 class="text-xl font-semibold leading-none tracking-tighter text-black">宗片 比呂夫</h4>
                        <p class="mt-2 text-base leading-relaxed text-gray-500">Munekata Hiro</p>
                    </div>
                </div>
            </div>
            <h2>Research staff</h2>
            <div class="flex items-center justify-center w-full px-5 py-6 mx-auto max-w-xl">
                <div id="narushima" class="bg-white shadow-xl rounded-xl overflow-hidden">
                    <img alt="team" class="w-32 h-32 mx-auto mt-4 rounded-full object-cover" src="https://storage.googleapis.com/indie-hackers.appspot.com/avatars/300x300_DUFTlhOdmSdoT9F4r1Woo40pyML2.webp">
                    <div class="p-6 text-center">
                        <h4 class="text-xl font-semibold leading-none tracking-tighter text-black">成島 哲也</h4>
                        <p class="mt-2 leading-relaxed text-gray-500" style="font-size: 12.5px; line-height:24px">Narushima Tetsuya</p>
                    </div>
                </div>
            </div>
            <h2>Ph.D students</h2>
            <div class="flex items-center justify-center w-full px-5 py-6 mx-auto max-w-xl">
                <div class="grid grid-cols-1 gap-4">
                    {% for member in members_PhD %} 
                        <div id="MyBtn{{member.id}}" class="bg-white shadow-xl rounded-xl overflow-hidden">
                            <img alt="team" class="w-32 h-32 mx-auto mt-4 rounded-full object-cover" src="https://storage.googleapis.com/indie-hackers.appspot.com/avatars/300x300_DUFTlhOdmSdoT9F4r1Woo40pyML2.webp">
                            <div class="p-6 text-center">
                                <h4 class="text-xl font-semibold leading-none tracking-tighter text-black">{{member.name}}</h4>
                                <p class="mt-2 text-base leading-relaxed text-gray-500">{{member.name_roman}}</p>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
            <h2>Master course students</h2>
            <!--プロフィール-->
            <div class="flex items-center justify-center w-full px-5 py-6 mx-auto max-w-xl">
                <div class="grid grid-cols-3 gap-4">
                    {% for member in members_master2 %}
                        <div id="MyBtn{{member.id}}" class="bg-white shadow-xl rounded-xl overflow-hidden">
                            <img alt="team" class="w-32 h-32 mx-auto mt-4 rounded-full object-cover" src="{{member.image.url}}">
                            <div class="p-6 text-center">
                                <h4 class="text-xl font-semibold leading-none tracking-tighter text-black">{{member.name}}</h4>
                                <p class="mt-2 text-base leading-relaxed text-gray-500">{{member.name_roman}}</p>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
            <h2>Bachelor students</h2>
        </div>
    </div>
</div>

<!--以下ポップアップ(モーダル)-->
<!--学生のポップアップ-->
{% for member in members_all %}
    <div id="memberModal{{member.id}}" class="modal">
        <div class="modal-content" style="max-width: 600px; min-height: 400px;">
            <span class="close">&times;</span>
            <div class="grid gap-5 mx-auto" style="padding: 20px;">
                <div class="flex flex-col  md:flex-row overflow-hidden rounded-lg shadow-lg bg-white">
                    <div class="px-2 flex-shrink-0 w-full md:w-1/3" style="height: 250px; display: flex; justify-content: center; align-items: center;">
                        <!-- 画像が縮小して収まるように `scale-down` を使用 -->
                        {% if member.image %}
                            <img alt="{{ member.name }}" class="object-scale-down h-full" src="{{ member.image.url }}">
                        {% else %}
                            <img alt="default" class="object-scale-down h-full" src="https://images.unsplash.com/photo-1561654791-00316c79efa8?ixlib=rb-1.2.1&amp;ixid=MnwxMjA3fDB8MHxwaG90by1yZWxhdGVkfDE5fHx8ZW58MHx8fHw%3D&amp;auto=format&amp;fit=crop&amp;w=900&amp;q=60">
                        {% endif %}
                    </div>
                    <div class="flex-1 p-5">
                        <p class="text-center text-xl font-semibold text-black">{{ member.name }}<br></p>
                        <p class="text-center text-sm text-gray-500">{{ member.name_roman }}</p>
                        <p class="mt-3 text-black">Research</p>
                        <p class="mt-2 text-gray-500">{{ member.research }}</p>
                        <p class="mt-3 text-black">Brief Comment</p>
                        <p class="mt-2 text-gray-500">{{ member.comment }}</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endfor %}
<!--教員のポップアップ。これは別HTMLから引っ張ってくる-->
    <div id="Modal_yamada">aa</div>
    {% include "member_templete/all_templete.html" %}
<script>
//背景画像のフェードイン
document.addEventListener("DOMContentLoaded", function() {
    setTimeout(function() {
        var memberElement = document.getElementById('member');
        memberElement.style.opacity = "1";
        memberElement.style.visibility = "visible";
    }, 100); // 0.1秒後に実行
});

    //フェードインの設定
window.onload=function(){
    setTimeout(function(){
        var bodyelement = document.getElementById('body');
        bodyelement.classList.add('body_active');
    },1500);
}
    //member.idにより識別されるモーダルを表示
document.addEventListener("DOMContentLoaded", function() {
    // すべての閉じるボタンに対するイベントリスナーを設定
    document.querySelectorAll('.close').forEach(function(span) {
        span.onclick = function() {
            // この閉じるボタンが属するモーダルを非表示にする
            this.closest('.modal').style.display = 'none';
        };
    });

    // モーダルの外側をクリックした場合にモーダルを閉じる
    document.querySelectorAll('.modal').forEach(function(modal) {
        modal.onclick = function(event) {
            if (event.target == modal) {
                modal.style.display = 'none';
            }
        };
    });

    // 各ボタンに対してイベントリスナーを設定
    document.querySelectorAll("[id^='MyBtn']").forEach(function(btn) {
        btn.onclick = function() {
            // ボタンのIDから対応するモーダルのIDを導出
            var modalId = 'memberModal' + btn.id.replace('MyBtn', '');
            var modal = document.getElementById(modalId);
            if (modal) {
                modal.style.display = 'flex';
            }
        };
    });
});
</script>
<style>
    [id^='MyBtn'] {
        cursor: pointer;
    }
</style>
{% endblock %}

ocmpHP/templates/toppage.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<section class="toppage">
    <div class="toppage-text">
        <span>Welcome to</span>
        <h1>Satoh laboratory</h1>
        <p>佐藤研究室では超短パルスレーザーを用いた磁性体の制御・測定に挑戦しています。</p>
    </div>

    <!--<div class="toppage-img">
        <img src="{%static 'img/Hysteresis.png'%}">
    </div>-->
</section>


 佐藤研究室です．
 <p>ここに文章を書く．</p>
 <p>ここに文章を書く．</p>
 <p>ここに文章を書く．</p>
 <p>ここに文章を書く．</p>
 <p>ここに文章を書く．</p>
 <p>ここに文章を書く．</p>
 <p>ここに文章を書く．</p>
 <p>ここに文章を書く．</p>
 <p>ここに文章を書く．</p>
 <p>ここに文章を書く．</p>
 <p>ここに文章を書く．</p>
 <p>ここに文章を書く．</p>
 <p>ここに文章を書く．</p>
 <p>ここに文章を書く．</p>
 <p>ここに文章を書く．</p>
 <p>ここに文章を書く．</p>
 <p>ここに文章を書く．</p>
 <p>ここに文章を書く．</p>
 <p>ここに文章を書く．</p>
 <p>ここに文章を書く．</p>
 <p>ここに文章を書く．</p>
 <p>ここに文章を書く．</p>
 <p>ここに文章を書く．</p>
 <p>ここに文章を書く．</p>
 <p>ここに文章を書く．</p>
 <p>ここに文章を書く．</p>
 <p>ここに文章を書く．</p>
 <p>ここに文章を書く．</p>
 <p>ここに文章を書く．</p>
 <p>ここに文章を書く．</p>
 <p>ここに文章を書く．</p>
 <p>ここに文章を書く．</p>
 <p>ここに文章を書く．</p>
 <p>ここに文章を書く．</p>
 <p>ここに文章を書く．</p>
 <p>ここに文章を書く．</p>
 <p>ここに文章を書く．</p>
 <p>ここに文章を書く．</p>
 <p>ここに文章を書く．</p>
 <p>ここに文章を書く．</p>
 <p>ここに文章を書く．</p>
 <p>ここに文章を書く．</p>
 <p>ここに文章を書く．</p>
 <p>ここに文章を書く．</p>
 <style>
        .toppage{
            background-image:url("{%static 'img/space.jpg'%}");/*notionのメモも参照*/
            width:100%;
            height:100vh;
            background-position: center;
            background-size: cover;
        }
 </style>
{% endblock %}

ocmpHP/templates/toppage/index.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<section class="toppage">
    <div class="toppage-text">
        <span>Welcome to</span>
        <h1>Satoh laboratory</h1>
        <p>佐藤研究室では超短パルスレーザーを用いた磁性体の制御・測定に挑戦しています。</p>
    </div>

    <!--<div class="toppage-img">
        <img src="{%static 'img/Hysteresis.png'%}">
    </div>-->
</section>


 佐藤研究室です．
 <p>ここに文章を書く．</p>
 <p>ここに文章を書く．</p>
 <p>ここに文章を書く．</p>
 <p>ここに文章を書く．</p>
 <p>ここに文章を書く．</p>
 <p>ここに文章を書く．</p>
 <p>ここに文章を書く．</p>
 <p>ここに文章を書く．</p>
 <p>ここに文章を書く．</p>
 <p>ここに文章を書く．</p>
 <p>ここに文章を書く．</p>
 <p>ここに文章を書く．</p>
 <p>ここに文章を書く．</p>
 <p>ここに文章を書く．</p>
 <p>ここに文章を書く．</p>
 <p>ここに文章を書く．</p>
 <p>ここに文章を書く．</p>
 <p>ここに文章を書く．</p>
 <p>ここに文章を書く．</p>
 <p>ここに文章を書く．</p>
 <p>ここに文章を書く．</p>
 <p>ここに文章を書く．</p>
 <p>ここに文章を書く．</p>
 <p>ここに文章を書く．</p>
 <p>ここに文章を書く．</p>
 <p>ここに文章を書く．</p>
 <p>ここに文章を書く．</p>
 <p>ここに文章を書く．</p>
 <p>ここに文章を書く．</p>
 <p>ここに文章を書く．</p>
 <p>ここに文章を書く．</p>
 <p>ここに文章を書く．</p>
 <p>ここに文章を書く．</p>
 <p>ここに文章を書く．</p>
 <p>ここに文章を書く．</p>
 <p>ここに文章を書く．</p>
 <p>ここに文章を書く．</p>
 <p>ここに文章を書く．</p>
 <p>ここに文章を書く．</p>
 <p>ここに文章を書く．</p>
 <p>ここに文章を書く．</p>
 <p>ここに文章を書く．</p>
 <p>ここに文章を書く．</p>
 <p>ここに文章を書く．</p>
 <style>
        .toppage{
            background-image:url("{%static 'img/space.jpg'%}");/*notionのメモも参照*/
            width:100%;
            height:100vh;
            background-position: center;
            background-size: cover;
        }
 </style>
{% endblock %}

ocmpHP/theme/templates/base.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
	<head>
    <title>Django Tailwind</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta http-equiv="X-UA-Compatible" content="ie=edge">
		{% tailwind_css %}
	</head>

	<body class="bg-gray-50 font-serif leading-normal tracking-normal">
		<div class="container mx-auto">
			<section class="flex items-center justify-center h-screen">
				<h1 class="text-5xl">Django + Tailwind = ❤️</h1>
			</section>
		</div>
	</body>
</html>